" make sure not to use vi compatibility mode
set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required. Install in vim running :PluginInstall 
Plugin 'VundleVim/Vundle.vim'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-surround'
Plugin 'jiangmiao/auto-pairs'
Plugin 'itchyny/lightline.vim'

" All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on


" enable syntax highlighting
syntax enable
" set number
set number 
set relativenumber

" set scrolloff
set scrolloff=8

" set hidden
set hidden

" set search options
set incsearch
set hlsearch
set ignorecase
set smartcase

" show commands as you type them
set showcmd

" Tab options
set expandtab
set shiftwidth=8
set tabstop=8
set softtabstop=8

" set stricterfor c programming
set cindent
set autoindent
set smartindent

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

colorscheme ron

map <F10>:%!astyle --style=kr --indent=spaces=8 --indent-switches --indent-classes --pad-oper --pad-header --unpad-paren --convert-tabs <CR>
:map <F9> :setlocal spell! spelllang=en_us<CR>

" fix ctags to search upper folders (use `ctags -R *` for creating tags recursive)
set tags=tags;
